server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              # uri: http://auth-service:8081
              uri: http://localhost:8081/
              predicates:
                - Path=/auth/**
                

            - id: property-service
              uri: http://property-service:8082
              predicates:
                - Path=/properties/**

            - id: notification-service
              uri: http://notification-service:8083
              predicates:
                - Path=/notifications/**

security:
  auth:
    validate-url: http://auth-service:8081/auth/validate


# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info
